### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [koko8puff/prj-rev-bwfs-dasmoto#4]
https://github.com/koko8puff/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L13-L32

You've got a lot of shared styles being needlessly repeated throughout your CSS rules.

Make sure to consolidate those into their own rule to keep your CSS maintainable.

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

If you had a `div` with a class of `product` you could write a better, more specific and more descriptive selector like `.product h2`.
